erDiagram
    USER ||--o{ EVENT : creates
    USER ||--o{ SWIPE : performs
    USER ||--o{ USER_PREFERENCE : selects
    USER ||--o{ EVENT_CHAT : sends
    USER ||--o{ NOTIFICATION : receives
    USER ||--o{ USER_RATING : receives_rating
    USER ||--o{ EVENT_RATING : gives_rating
    USER ||--o{ ATTENDANCE : attends


    EVENT ||--o{ SWIPE : receives
    EVENT ||--o{ EVENT_CHAT : hosts
    
    CATEGORY ||--o{ EVENT : categorizes
    CATEGORY ||--o{ USER_PREFERENCE : used_in 

    USER {
        int id PK
        varchar name
        varchar email
        varchar password_hash
        text bio
        int age
        varchar profile_pic
        timestamp created_at
    }
    EVENT {
        int id PK
        int creator_id FK
        int category_id FK
        varchar title
        text description
        datetime event_date
        varchar location_name
        decimal lat 
        decimal long
        varchar event_pic
        timestamp created_at
    }
    USER_RATING {
        int id PK
        int rater_id FK 
        int ratee_id FK 
        int score 
        text comment
        timestamp created_at
    }
    EVENT_RATING {
        int id PK
        int user_id FK
        int event_id FK
        int score
        text review
    }
    ATTENDANCE {
        int id PK
        int user_id FK
        int event_id FK
        timestamp check_in_time
    }
    CATEGORY {
        int id PK
        varchar name
    }
    SWIPE {
        int id PK
        int user_id FK
        int event_id FK
        boolean is_interested
        timestamp created_at
    }
    USER_PREFERENCE {
        int user_id FK
        int category_id FK
    }
    EVENT_CHAT {
        int id PK
        int event_id FK
        int user_id FK
        text message
        timestamp sent_at
    }
    NOTIFICATION {
        int id PK
        int user_id FK
        varchar content
        boolean is_read
    }