import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import joinMeApi from "./docs/api-specs/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  apiSidebar: [
    {
      type: 'category',
      label: 'JoinMe API',
      link: {
        type: 'generated-index',
        title: 'JoinMe API',
        description: 'JoinMe API Specifications',
        slug: '/category/api'
      },
      items: joinMeApi
    }
  ],
};

export default sidebars;
